name: Test:CI Pipeline

on:
  workflow_dispatch:
    inputs:
      job_to_run:
        description: '実行するCIを選択してください'
        required: true
        type: choice
        options:
          - ci_test

env:
  TF_WORKING_DIR: ./terraform
  TF_VERSION: 1.13.4

jobs:
  ci:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.job_to_run == 'ci_test'
    permissions:
      id-token: write

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      # python環境のセットアップ
      - name: Python環境のセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 必要ライブラリのインストール
      - name: 依存関係とCIツールのインストール
        run: |
          pip install -r requirements/requirements_ci.txt

      # 静的解析
      - name: コードのLintチェック
        run: flake8 --ignore=E501,W503,F401,F403 ./src

      # Python単体テストの実行
      - name: Pytestによる単体テスト
        run: pytest tests/

      # Terraformの検証
      - name: Terraformのセットアップ
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # GCPのセットアップ
      - name: GCPサービスアカウントキーのセットアップ
        run: |
          printf '%s' '${{ secrets.BIGQUERY_SA_KEY_JSON }}' > ${{ runner.temp }}/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/gcp-key.json" >> $GITHUB_ENV
      
      # ASWのセットアップ
      - name: AWS認証情報の構成 (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Terraform Validate 
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      # Terraform Plan
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var="youtube_api_key=${{ secrets.YOUTUBE_API_KEY }}" \
            -var='bigquery_sa_key_json=${{ secrets.BIGQUERY_SA_KEY_JSON }}' \
            -var="alert_email_endpoint=${{ secrets.ALERT_EMAIL_ENDPOINT }}" \
            -var="gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="gcp_region=${{ secrets.GCP_REGION }}" \
            -out=tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}