name: Test:CI Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  TF_WORKING_DIR: ./terraform
  TF_VERSION: 1.13.4

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: コードのチェックアウト
        uses: actions/checkout@v4

      - name: AWS認証情報の構成 (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_CI }}
          aws-region: ${{ secrets.AWS_REGION }}

      # python環境のセットアップ
      - name: Python環境のセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 必要ライブラリのインストール
      - name: 依存関係とCIツールのインストール
        run: |
          pip install -r requirements_ci.txt
          pip install flake8 pytest

      # 静的解析
      - name: コードのLintチェック
        run: flake8 ./src

      # Python単体テストの実行
      - name: Pytestによる単体テスト
        run: pytest ./src/tests

      # Terraformの検証
      - name: Terraformのセットアップ
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
          
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan (変更点の確認)
        run: terraform plan
        working-directory: ${{ env.TF_WORKING_DIR }}